---

- name: "Replace Configuration on CSR using RestConf"
  hosts: R1
  connection: local
  tasks:
    - name: "TASK 1 - Configure OSPF"
      uri:
        url: "https://{{ ansible_host }}/restconf/data/native/router"
        method: PUT
        validate_certs: false
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        headers:
          Accept:
            application/yang-data+json,
            application/yang-data.erros+json
          Content-Type: "application/yang-data+json"
        body_format: json
        body: "{{ configure_ospf }}"
        status_code:
          - 200
          - 204
