---

- name: "PLAY 1: Gather local host facts"
  hosts: localhost

  tasks:
    - name: "TASK 1 of PLAY 1: Gathering Facts"
      ansible.builtin.setup:
        filter:
          - "ansible_date_time"

    - name: "TASK 2 of PLAY 1: Recording a Variable"
      set_fact:
        TD: "{{ ansible_date_time.date }}"
    
    - name: "TASK 3 of PLAY 1: Creating Directories"
      ansible.builtin.file:
        path: "Backups/{{ TD }}"
        state: "directory"
      run_once: true

- name: " PLAY 2: Gathering Backups"
  hosts: all
  connection: network_cli

  tasks:
    - name: "TASK 1 of PLAY 2: Pull Configuration from Remote Devices"
      napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        dev_os: "{{ napalm_platform }}"
        filter: ["config"]
      register: config_output

    - name: "TASK 2 of PLAY 2: Create Startup Config Subdirectory"
      file:
        path: "Backups/{{ hostvars.localhost.TD }}/startup-config"
        state: directory
      run_once: true

    - name: "TASK 3 of PLAY 2: Create Running Config Subdirectory"
      file:
        path: "Backups/{{ hostvars.localhost.TD }}/running-config"
        state: directory
      run_once: true

    - name: "TASK 4 of PLAY 2: Saving Startup Configuration"
      copy:
        content: "{{ config_output.ansible_facts.napalm_config.startup}}"
        dest: "Backups/{{ hostvars.localhost.TD }}/startup-config/{{inventory_hostname}}-startup-config.txt"

    - name: "TASK 5 of PLAY 2: Saving Startup Configuration"
      copy:
        content: "{{ config_output.ansible_facts.napalm_config.running}}"
        dest: "Backups/{{ hostvars.localhost.TD }}/running-config/{{inventory_hostname}}-running-config.txt"

