---

- name: "Syslog configuration"
  connection: network_cli
  hosts: cisco

  tasks:

    - name: "Configure Syslog Host IP"
      cisco.ios.ios_logging_global:
        config:
          hosts:
            - hostname: "{{ item.ip }}"

        state: merged

      loop: "{{ syslog.hosts }}"
      when: item.port is not defined
      register: task1_output

    - name: "Configure Syslog Host IP + Port"
      cisco.ios.ios_logging_global:
        config:
          hosts:
            - hostname: "{{ item.ip }}"
              transport:
                tcp:
                  port: "{{ item.port }}"
        state: merged
      loop: "{{ syslog.hosts }}"
      when: item.port is  defined
      register: task2_output

    - name: "TASK 1 Output"
      debug:
        msg: "{{item.commands }}"
      loop: "{{ task1_output.results }}"
      loop_control:
        label: none
      when: item.commands is defined 

    - name: "TASK 2 Output"
      debug:
        msg: "{{item.commands }}"
      loop: "{{ task2_output.results }}"
      loop_control:
        label: none
      when: item.commands is defined 
