syslog:
  hosts:
    - ip: "1.1.1.1"

    - ip: "2.2.2.2"
      port: "514"

    - ip: "3.3.3.3"

    - ip: "4.4.4.4"
      port: "1111"


configure_ospf:
  Cisco-IOS-XE-native:router:
    Cisco-IOS-XE-ospf:router-ospf:
      ospf:
        process-id:
        - id: 1
          network:
          - area: 0
            ip: 10.0.0.0
            wildcard: 0.0.0.255
          - area: 55
            ip: 11.11.11.0
            wildcard: 0.0.255.255
          - area: 10
            ip: 55.55.55.55
            wildcard: 0.0.0.0
          router-id: 1.1.1.1